<?php

namespace AppBundle\Repository;

/**
 * MemberAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
  
}
