<?php

namespace AppBundle\Repository;

/**
 * ProjectTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTitleRepository extends \Doctrine\ORM\EntityRepository
{

}
